name: ESLint&tests-check

on: push

jobs:
  ESLint:
    name: Lint code base
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: 'package-lock.json'

      - name: Install dependencies
        run: npm ci

      - name: Lint
        run: make lint

      - name: Run tests with coverage
        run: |
          NODE_OPTIONS=--no-experimental-fetch npm test -- --coverage --coverageProvider=v8

      - name: Download CodeClimate Test Reporter
        run: |
          curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-reporter
          chmod +x ./cc-reporter

      - name: CodeClimate before-build
        run: ./cc-reporter before-build

      - name: CodeClimate after-build
        run: |
          ./cc-reporter format-coverage -t lcov -o codeclimate.json coverage/lcov.info
          ./cc-reporter upload-coverage
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
